name: CI/CD Simulado - QA

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar ambiente de prueba
        run: echo "Configurando entorno de CI/CD para QA"

      - name: Ejecutar prueba simulada
        run: echo "Ejecutando pruebas automatizadas..."

      - name: Validar resultados
        run: echo "Validación completada exitosamente"
